name: Waka Readme

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          # Your GitHub token
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # Show all-time stats
          RANGE: all_time

          # Optional
          SHOW_TIME: true
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
